version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      ONLINE_MODE: "FALSE"
      TYPE: "MOHIST"
      VERSION: "1.19.2"
      INIT_MEMORY: "8G"
      MAX_MEMORY: "16G"
      MEMORY: "16G"
      DIFFICULTY: "hard"
      MOTD: "СОСУ ХУЙ 24/7"
      SERVER_NAME: "ВЫ ГОТОВЫ?"
      ENABLE_AUTOPAUSE: "TRUE"
      AUTOPAUSE_TIMEOUT_EST: "10"
      AUTOPAUSE_TIMEOUT_INIT: "10"
      AUTOPAUSE_TIMEOUT_KN: "30"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      MAX_TICK_TIME: "-1"
    ports:
      - "25565:25565"
    volumes:
      - data:/data
      - ./mods:/data/mods
      - ./plugins:/data/plugins
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}