version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      ONLINE_MODE: "FALSE"
      TYPE: "FORGE"
      VERSION: "1.19.2"
      INIT_MEMORY: "4G"
      MAX_MEMORY: "8G"
      MEMORY: "8G"
      DIFFICULTY: "hard"
      SERVER_NAME: "СОСУ ХУЙ 24/7"
      MOTD: "ВЫ ГОТОВЫ?"
    ports:
      - "25565:25565"
    volumes:
      - data:/data
      - ./mods:/data/mods
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}